/**
 * Questions backed by the `candidates` table (`002_candidates.sql`) — the
 * account preamble, biodata, and family columns.
 *
 * Split from its siblings purely to stay under the repo's 300-line file cap;
 * the split follows the migration's table boundaries so each file has one
 * destination table.
 */

import {
  COMPLEXION_OPTIONS,
  DIET_OPTIONS,
  GENDER_OPTIONS,
  INCOME_BAND_OPTIONS,
  MARITAL_STATUS_OPTIONS,
  OWNER_TYPE_OPTIONS,
} from "./choices.ts";
import type { FormField } from "./types.ts";

export const CANDIDATE_FIELDS: readonly FormField[] = [
  // ── Getting started ────────────────────────────────────────────────
  {
    id: "owner_type",
    section: "account",
    table: "candidates",
    kind: "choice",
    prompt: "Who are you filling this in for?",
    options: OWNER_TYPE_OPTIONS,
    required: true,
  },
  {
    id: "language",
    section: "account",
    table: "candidates",
    kind: "text",
    prompt: "Which language are you most comfortable in?",
    hint: "For example: Hindi, Tamil, English",
    required: false,
  },

  // ── About you ──────────────────────────────────────────────────────
  {
    id: "full_name",
    section: "biodata",
    table: "candidates",
    kind: "text",
    prompt: "What's the full name?",
    required: true,
  },
  {
    id: "gender",
    section: "biodata",
    table: "candidates",
    kind: "choice",
    prompt: "Gender?",
    options: GENDER_OPTIONS,
    required: true,
  },
  {
    id: "dob",
    section: "biodata",
    table: "candidates",
    kind: "date",
    prompt: "Date of birth?",
    hint: "Format: DD/MM/YYYY — for example 14/03/1996",
    required: true,
  },
  {
    id: "birth_place",
    section: "biodata",
    table: "candidates",
    kind: "text",
    prompt: "Where were you born?",
    required: false,
  },
  {
    id: "city",
    section: "biodata",
    table: "candidates",
    kind: "text",
    prompt: "Which city do you live in now?",
    required: true,
  },
  {
    id: "height",
    section: "biodata",
    table: "candidates",
    kind: "integer",
    prompt: "Height, in centimetres?",
    hint: "Just the number — for example 170",
    required: false,
    min: 120,
    max: 230,
  },
  {
    id: "complexion",
    section: "biodata",
    table: "candidates",
    kind: "choice",
    prompt: "How would you describe your complexion?",
    options: COMPLEXION_OPTIONS,
    required: false,
  },
  {
    id: "marital_status",
    section: "biodata",
    table: "candidates",
    kind: "choice",
    prompt: "Current marital status?",
    options: MARITAL_STATUS_OPTIONS,
    required: true,
  },
  {
    id: "community",
    section: "biodata",
    table: "candidates",
    kind: "text",
    prompt: "Which community do you belong to?",
    hint: "For example: Garg (Mangal) — community name, gotra in brackets",
    required: false,
  },
  {
    id: "highest_education",
    section: "biodata",
    table: "candidates",
    kind: "text",
    prompt: "What's your highest qualification?",
    hint: "For example: B.Tech, MBA, B.Com",
    required: true,
  },
  {
    id: "occupation",
    section: "biodata",
    table: "candidates",
    kind: "text",
    prompt: "What do you do for work?",
    required: true,
  },
  {
    id: "income_band",
    section: "biodata",
    table: "candidates",
    kind: "choice",
    prompt: "Roughly what's your annual income?",
    options: INCOME_BAND_OPTIONS,
    required: false,
  },
  {
    id: "diet",
    section: "biodata",
    table: "candidates",
    kind: "choice",
    prompt: "What's your diet?",
    options: DIET_OPTIONS,
    required: false,
  },

  // ── Family ─────────────────────────────────────────────────────────
  {
    id: "father_name",
    section: "family",
    table: "candidates",
    kind: "text",
    prompt: "Father's name?",
    required: false,
  },
  {
    id: "father_occupation",
    section: "family",
    table: "candidates",
    kind: "text",
    prompt: "What does your father do?",
    required: false,
  },
  {
    id: "mother_name",
    section: "family",
    table: "candidates",
    kind: "text",
    prompt: "Mother's name?",
    required: false,
  },
  {
    id: "mother_occupation",
    section: "family",
    table: "candidates",
    kind: "text",
    prompt: "What does your mother do?",
    required: false,
  },
  {
    id: "brothers",
    section: "family",
    table: "candidates",
    kind: "integer",
    prompt: "How many brothers do you have?",
    hint: "Enter 0 if none",
    required: false,
    min: 0,
    max: 20,
  },
  {
    id: "brothers_married",
    section: "family",
    table: "candidates",
    kind: "integer",
    prompt: "How many of them are married?",
    required: false,
    min: 0,
    max: 20,
  },
  {
    id: "sisters",
    section: "family",
    table: "candidates",
    kind: "integer",
    prompt: "How many sisters do you have?",
    hint: "Enter 0 if none",
    required: false,
    min: 0,
    max: 20,
  },
  {
    id: "sisters_married",
    section: "family",
    table: "candidates",
    kind: "integer",
    prompt: "How many of them are married?",
    required: false,
    min: 0,
    max: 20,
  },
] as const;
